- name: jar deploy
  sudo: yes
  hosts: "{{ hosts }}"
  tasks:
      # https://gist.github.com/halberom/7ba0b251a45291621be4
    - name: check if we have a systemd service setup
      stat: "path=/etc/systemd/system/{{service_name}}.service"
      register: service_stat


    - name: check if we have a dir for this service
      stat: "path=/home/{{user_name}}/{{service_name}}/"
      register: dir_stat


    - name: create dir if not exists
      file:
        path: "/home/{{user_name}}/{{service_name}}/"
        state: directory
        owner: "{{user_name}}"
        group: "{{user_name}}"
        mode: 0755
      when: dir_stat.stat.exists == false


    - name: copy jar up
      copy:
        src: "{{ jar_local_dir }}{{ jar_local_filename}}"
        dest: "/home/{{user_name}}/{{service_name}}/{{ jar_local_filename}}"


    - name: create service if needed
      template:
        src: ./templates/java.service.j2
        dest: "/etc/systemd/system/{{service_name}}.service"
        owner: "{{user_name}}"
        group: wheel
      when: service_stat.stat.exists == false

    
    - name: reload service
      systemd:
        state: restarted
        name: "{{service_name}}.service"
